font_family BerkeleyMono Nerd Font Mono Regular
bold_font BerkeleyMono Nerd Font Mono Bold
italic_font BerkeleyMono Nerd Font Mono Italic
bold_italic_font BerkeleyMono Nerd Font Mono Italic

font_size 13
modify_font cell_height 180%

cursor_shape beam
window_resize_step_cells 2
window_resize_step_lines 2
initial_window_width 640
initial_window_height 400
draw_minimal_borders yes
macos_titlebar_color background
enable_audio_bell no

include gruvbox.conf
