font_family JetBrainsMono Nerd Font Mono

font_size 14
adjust_line_height 175%

cursor_blink_interval 0
enable_audio_bell 0
window_padding_width 0 10


# BEGIN_KITTY_THEME
# Catppuccin-Frappe
include current-theme.conf
# END_KITTY_THEME

macos_titlebar_color background
